server:
  port: 8080

app:
  init-data: false
  jwtSecret: "myVerySecretKeyThatIsAtLeast256BitsLongForHMACSecurityPurposes="
  jwtExpirationMs: 86400000  # 24 hours

spring:
  application:
    name: Tennis Club
  profiles:
    active: dev

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

  jackson:
    serialization:
      write-dates-as-timestamps: false